### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by zooool** [mariusor/brutalinks#49]
-Auto fetch and fill submission title based on the URL that's being input
-Add thumbnails (automatically fetched from the URL)
-Make links open in new tabs with noopener/noreferrer/nofollow
-Create a sitename config so the browser tab doesn't just display "Newest items"

**Comment by mariusor** [comment]
Thank you for your input, but I don't really accept feature requests on github.

I will definitely not add thumbnails and opening in a new tab options. The prime directive of the "Brutalist Links - Brutalinks" project is to be very minimal in its interface.

For the other two, please feel free to write to the [mailing list](https://lists.sr.ht/~mariusor/go-activitypub-discuss).

**Comment by zooool** [comment]
> For the other two, please feel free to write to the [mailing list](https://lists.sr.ht/~mariusor/go-activitypub-discuss).

I'm not 70+ years old so I certainly will not be using a "mailing list".

**Comment by mariusor** [comment]
Cool.
